import './globals.css'
import type { Metadata } from 'next'
import Header from './components/Header'
import Footer from './components/Footer'
import { Sora } from "next/font/google"

export const sora = Sora({
  subsets:['latin'],
  weight:['400','700']
})

export const metadata: Metadata = {
  title: 'Data People',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <div className={sora.className}>
        <Header />
        {children}
        <Footer />
      </div>

    </>
  );
};
